名称：构建 luci-app-igmpproxy

在:
  工作流触发:

# 必须添加的权限设置
权限:
  目录: 写

工作:
  构建:
    运行于：ubuntu-latest
    名称: 构建 luci-app-igmpproxy (OpenWrt 快照 - qualcommax/ipq60xx)
    
    步骤:
      - 名称: 检出仓库
        使用：actions/checkout@v4
        与：
          取深度：0  # 必须添加，否则无法创建标签

      - 名称: 安装依赖项
        运行： |
          sudo apt-get update
          请将以下文本翻译成中文:           sudo apt-get install -y \
            build-essential ccache fastjar file g++ gawk gettext git libelf-dev \
            libncurses5-dev libncursesw5-dev libssl-dev python3 python3-pip
            python3-setuptools rsync unzip wget zlib1g-dev xz-utils zstd

      - 名称: 下载 OpenWrt SDK
        运行： |
          wget https://mirror-03.infra.openwrt.org/snapshots/targets/qualcommax/ipq60xx/openwrt-sdk-qualcommax-ipq60xx_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xf openwrt-sdk-qualcommax-ipq60xx_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          mv openwrt-sdk-qualcommax-ipq60xx_gcc-14.3.0_musl.Linux-x86_64 openwrt-sdk

      - 名称: 准备包裹
        运行： |
          mkdir -p openwrt-sdk/package/luci-app-igmpproxy
          rsync -av --delete \
            --exclude 'openwrt-sdk' \
            --exclude '.git' \
            --exclude 'bin' \
            --exclude '.github/workflows' \
            --exclude '*.tar.zst' \
            ./ openwrt-sdk/package/luci-app-igmpproxy/

      - name: Build package
        working-directory: openwrt-sdk
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/luci-app-igmpproxy/compile V=s
          
          # 调试：确认文件生成路径
          find bin/packages -name "luci-app-igmpproxy*" -ls
          echo "Generated files:"
          ls -la bin/packages/*/*/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-igmpproxy
          path: |
            openwrt-sdk/bin/packages/**/luci-app-igmpproxy*.apk
            openwrt-sdk/bin/packages/**/luci-app-igmpproxy*.ipk
          if-no-files-found: error

      - name: Setup Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create and push tag
        run: |
          TAG="v$(date +'%Y.%m.%d-%H%M')"
          git tag $TAG
          git push origin $TAG

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            openwrt-sdk/bin/packages/**/luci-app-igmpproxy*.apk
            openwrt-sdk/bin/packages/**/luci-app-igmpproxy*.ipk
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
