name: Build luci-app-igmpproxy Multi-Arch

on:
  workflow_dispatch:

# 必须添加的权限设置
permissions:
  contents: write
  packages: write

jobs:
  build-multi-arch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - name: "qualcommax-ipq60xx-snapshot"
            sdk_url: "https://mirror-03.infra.openwrt.org/snapshots/targets/qualcommax/ipq60xx/openwrt-sdk-qualcommax-ipq60xx_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
            archive_type: "zstd"
            extract_cmd: "tar -I zstd -xf"
          - name: "mediatek-filogic-23.05.0"
            sdk_url: "https://downloads.openwrt.org/releases/23.05.0/targets/mediatek/filogic/openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
            archive_type: "xz"
            extract_cmd: "tar -xJf"

    name: Build luci-app-igmpproxy (${{ matrix.target.name }})
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 必须添加，否则无法创建标签

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential ccache fastjar file g++ gawk gettext git libelf-dev \
            libncurses5-dev libncursesw5-dev libssl-dev python3 python3-pip \
            python3-setuptools rsync unzip wget zlib1g-dev xz-utils zstd

      - name: Download OpenWrt SDK
        run: |
          wget ${{ matrix.target.sdk_url }} -O sdk-archive
          ${{ matrix.target.extract_cmd }} sdk-archive
          # 自动检测并重命名 SDK 目录
          SDK_DIR=$(tar -tf sdk-archive | head -1 | cut -f1 -d"/")
          mv "$SDK_DIR" openwrt-sdk

      - name: Prepare package
        run: |
          mkdir -p openwrt-sdk/package/luci-app-igmpproxy
          rsync -av --delete \
            --exclude 'openwrt-sdk' \
            --exclude '.git' \
            --exclude 'bin' \
            --exclude '.github/workflows' \
            --exclude '*.tar.*' \
            --exclude 'sdk-archive' \
            ./ openwrt-sdk/package/luci-app-igmpproxy/

      - name: Build package
        working-directory: openwrt-sdk
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/luci-app-igmpproxy/compile V=s
          
          # 调试：确认文件生成路径
          echo "=== 生成的文件列表 ==="
          find bin/packages -name "luci-app-igmpproxy*" -o -name "luci-i18n-igmpproxy*" | while read file; do
            echo "找到文件: $file"
            ls -la "$file"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-igmpproxy-${{ matrix.target.name }}
          path: |
            openwrt-sdk/bin/packages/**/luci-app-igmpproxy*
            openwrt-sdk/bin/packages/**/luci-i18n-igmpproxy*
          retention-days: 7
          if-no-files-found: warn

      - name: Copy packages to staging
        run: |
          mkdir -p packages-staging/${{ matrix.target.name }}
          cp openwrt-sdk/bin/packages/**/luci-app-igmpproxy* packages-staging/${{ matrix.target.name }}/ 2>/dev/null || true
          cp openwrt-sdk/bin/packages/**/luci-i18n-igmpproxy* packages-staging/${{ matrix.target.name }}/ 2>/dev/null || true
          
          echo "=== 复制到暂存区的文件 ==="
          ls -la packages-staging/${{ matrix.target.name }}/

      - name: Upload packages to staging
        uses: actions/upload-artifact@v4
        with:
          name: all-packages-staging
          path: packages-staging/
          retention-days: 1
          if-no-files-found: warn

  create-release:
    runs-on: ubuntu-latest
    name: Create Release and Upload Packages
    needs: build-multi-arch
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all packages
        uses: actions/download-artifact@v4
        with:
          pattern: all-packages-staging
          path: downloaded-packages

      - name: Setup Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create version tag
        run: |
          TAG="v$(date +'%Y.%m.%d-%H%M')"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag $TAG
          git push origin $TAG

      - name: List all package files
        run: |
          echo "=== 准备发布的文件列表 ==="
          find downloaded-packages -type f -name "*.ipk" -o -name "*.apk" | while read file; do
            echo "发布文件: $file"
            ls -la "$file"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "luci-app-igmpproxy Build ${{ env.TAG }}"
          body: |
            Multi-architecture build of luci-app-igmpproxy
            
            **支持的架构:**
            - qualcommax/ipq60xx (OpenWrt Snapshots)
            - mediatek/filogic (OpenWrt 23.05.0)
            
            **包含的文件:**
            - luci-app-igmpproxy (主程序)
            - luci-i18n-igmpproxy-zh-cn (中文语言包)
            
            **构建时间:** ${{ github.workflow_run.created_at }}
          files: |
            downloaded-packages/**/*.ipk
            downloaded-packages/**/*.apk
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
